set encoding=utf-8
set number relativenumber
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set laststatus=2
set noshowmode
set showcmd
set bs=2

au BufWinLeave ?* mkview
au BufWinEnter ?* silent loadview

" pyhton host (faster startup)
let g:python3_host_prog = '/bin/python3'

" Plugins Start
call plug#begin('~/.vim/plugged')

" Nord color theme
Plug 'arcticicestudio/nord-vim'

"   lightline
Plug 'itchyny/lightline.vim'

let g:lightline = { 'colorscheme': 'nord' }

"   NERDTree
Plug 'preservim/nerdtree'

let g:NERDTreeShowHidden=1

map <F4> :NERDTreeToggle<CR>

"   gitgutter
Plug 'airblade/vim-gitgutter'

"   YCM
function! BuildYCM(info)
  " info is a dictionary with 3 fields
  " - name:   name of the plugin
  " - status: 'installed', 'updated', or 'unchanged'
  " - force:  set on PlugInstall! or PlugUpdate!
  if a:info.status == 'installed' || a:info.force
    !./install.py --clangd-completer --go-completer --ts-completer --rust-completer
  endif
endfunction
Plug 'ycm-core/YouCompleteMe', { 'do': function('BuildYCM') }
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable'}

let g:ycm_clangd_binary_path = "/usr/local/clangd_11.0.0/bin/clangd"
let g:ycm_confirm_extra_conf = 0
let g:ycm_language_server =
\ [
\   {
\     'name': 'rust',
\     'cmdline': ['rust-analyzer'],
\     'filetypes': ['rust'],
\     'project_root_files': ['Cargo.toml']
\   }
\ ]

map <F12> :YcmCompleter GoTo<CR>

" Plugins End
call plug#end()

colorscheme nord

